apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
spec:
  selector:
    app: hello-world
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: LoadBalancer
